---
# Source: rasa/charts/postgresql/templates/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: rasa-postgresql-headless
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.16.2
    app.kubernetes.io/instance: rasa
    app.kubernetes.io/managed-by: Helm
    # Use this annotation in addition to the actual publishNotReadyAddresses
    # field below because the annotation will stop being respected soon but the
    # field is broken in some versions of Kubernetes:
    # https://github.com/kubernetes/kubernetes/issues/58662
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  namespace: foreman
spec:
  type: ClusterIP
  clusterIP: None
  # We want all pods in the StatefulSet to have their addresses published for
  # the sake of the other Postgresql pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: rasa
---
# Source: rasa/charts/postgresql/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: rasa-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.16.2
    app.kubernetes.io/instance: rasa
    app.kubernetes.io/managed-by: Helm
  annotations:
  namespace: foreman
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: rasa
    role: primary
---
# Source: rasa/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rasa
  labels:
    helm.sh/chart: rasa-1.17.3
    app.kubernetes.io/name: rasa
    app.kubernetes.io/instance: rasa
    app.kubernetes.io/version: "3.2.6"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5005
      targetPort: http
      protocol: TCP
      name: http
    - port: 80
      targetPort: http-nginx
      protocol: TCP
      name: http-nginx
  selector:
    app.kubernetes.io/name: rasa
    app.kubernetes.io/instance: rasa
