---
# Source: rasa/templates/service.yaml
apiVersion: v1
kind: Service

metadata:
  name: rasa
  labels:
    helm.sh/chart: rasa-1.17.3
    app.kubernetes.io/name: rasa
    app.kubernetes.io/instance: rasa
    app.kubernetes.io/version: "3.2.6"
    app.kubernetes.io/managed-by: Helm

spec:
  type: ClusterIP
  ports:
    - port: 5005
      targetPort: http
      protocol: TCP
      name: http
    - port: 80
      targetPort: http-nginx
      protocol: TCP
      name: http-nginx
  selector:
    app.kubernetes.io/name: rasa
    app.kubernetes.io/instance: rasa
