apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: rasa

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: rasa
    creationPolicy: Owner
  dataFrom:
    - secretKey: .
      remoteRef:
        key: /schifferers/foreman/rasa/credentials
