---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: registry
  namespace: foreman

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .registry | toString }}"
    name: registry
    creationPolicy: Owner
  data:
    - secretKey: registry
      remoteRef:
        key: Registry

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: common
  namespace: foreman

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: common
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /schifferers/foreman/common/credentials
